import { Arrangement, NoteEvent, VOICES } from './types';
const encoder = new TextEncoder(); const bytes = (value: string) => Array.from(encoder.encode(value));
const u32 = (value: number) => [(value >>> 24) & 255, (value >>> 16) & 255, (value >>> 8) & 255, value & 255]; const u16 = (value: number) => [(value >>> 8) & 255, value & 255];
const variable = (value: number) => { const result = [value & 127]; while ((value >>= 7)) result.unshift((value & 127) | 128); return result; }; const chunk = (id: string, data: number[]) => [...bytes(id), ...u32(data.length), ...data];
function midiTrack(notes: NoteEvent[], name: string, tempo?: number) { const ticks = 480; const title = bytes(name); const events: { tick: number; data: number[] }[] = [{ tick: 0, data: [0xff, 0x03, ...variable(title.length), ...title] }]; if (tempo) { const micros = Math.round(60000000 / tempo); events.push({ tick: 0, data: [0xff, 0x51, 0x03, (micros >> 16) & 255, (micros >> 8) & 255, micros & 255] }); } notes.forEach(note => { const start = Math.round(note.start * 4 * ticks); const end = Math.round((note.start + note.duration) * 4 * ticks); events.push({ tick: start, data: [0x90, note.midi, note.velocity] }, { tick: end, data: [0x80, note.midi, 0] }); }); events.sort((a, b) => a.tick - b.tick || a.data[0] - b.data[0]); let last = 0; const data: number[] = []; events.forEach(event => { data.push(...variable(event.tick - last), ...event.data); last = event.tick; }); data.push(0, 0xff, 0x2f, 0); return chunk('MTrk', data); }
export function toMidi(arrangement: Arrangement): Blob { const tracks = [midiTrack([], arrangement.title, arrangement.tempo), ...VOICES.map(voice => midiTrack(arrangement.notes.filter(note => note.voice === voice), voice))]; return new Blob([new Uint8Array([...chunk('MThd', [...u16(1), ...u16(tracks.length), ...u16(480)]), ...tracks.flat()])], { type: 'audio/midi' }); }
const escapeXml = (value: string) => value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
function pitchXml(midi: number) { const names = [['C', 0], ['C', 1], ['D', 0], ['D', 1], ['E', 0], ['F', 0], ['F', 1], ['G', 0], ['G', 1], ['A', 0], ['A', 1], ['B', 0]] as const; const [step, alter] = names[midi % 12]; return `<pitch><step>${step}</step>${alter ? `<alter>${alter}</alter>` : ''}<octave>${Math.floor(midi / 12) - 1}</octave></pitch>`; }
export function toMusicXml(arrangement: Arrangement): Blob { const parts = VOICES.map((voice, index) => `<score-part id="P${index + 1}"><part-name>${voice}</part-name></score-part>`).join(''); const bodies = VOICES.map((voice, partIndex) => { const measures = arrangement.bars.map(bar => { const notes = arrangement.notes.filter(note => note.voice === voice && note.bar === bar.number); const attributes = bar.number === 1 ? `<attributes><divisions>24</divisions><key><fifths>0</fifths></key><time><beats>${arrangement.meter.split('/')[0]}</beats><beat-type>${arrangement.meter.split('/')[1]}</beat-type></time><clef><sign>${partIndex < 2 ? 'G' : partIndex < 4 ? 'C' : 'F'}</sign><line>${partIndex < 2 ? 2 : partIndex < 4 ? 3 : 4}</line></clef></attributes><direction><sound tempo="${arrangement.tempo}"/></direction>` : ''; const harmony = `<direction><direction-type><words>${escapeXml(bar.chord)}</words></direction-type></direction>`; const noteXml = notes.map(note => `<note>${pitchXml(note.midi)}<duration>${Math.max(1, Math.round(note.duration * 96))}</duration><voice>1</voice><type>quarter</type></note>`).join(''); return `<measure number="${bar.number}">${attributes}${harmony}${noteXml}</measure>`; }).join(''); return `<part id="P${partIndex + 1}">${measures}</part>`; }).join(''); const xml = `<?xml version="1.0" encoding="UTF-8"?><score-partwise version="4.0"><work><work-title>${escapeXml(arrangement.title)}</work-title></work><part-list>${parts}</part-list>${bodies}</score-partwise>`; return new Blob([xml], { type: 'application/vnd.recordare.musicxml+xml' }); }
export function toChart(arrangement: Arrangement): Blob { const lines = [arrangement.title, `${arrangement.style} | ${arrangement.key} ${arrangement.mode} | ${arrangement.meter} | ${arrangement.tempo} BPM`, '', ...(['A1', 'A2', 'B', 'A3'] as const).flatMap(section => [`[${section}]`, arrangement.bars.filter(bar => bar.section === section).map(bar => `${String(bar.number).padStart(2, '0')} | ${bar.chord.padEnd(15)} | ${bar.texture}`).join('\n'), ''])]; return new Blob([lines.join('\n')], { type: 'text/plain;charset=utf-8' }); }
export function download(blob: Blob, filename: string) { const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = filename; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
