import { useMemo, useState } from 'react';
import { Download, RefreshCw, Sparkles } from 'lucide-react';
import { arrange, STYLE_PRESETS } from '../arranger/engine';
import { download, toChart, toMidi, toMusicXml } from '../arranger/exporters';
import { VOICES } from '../arranger/types';
const KEYS = ['C', 'Db', 'D', 'Eb', 'E', 'F', 'F#', 'G', 'Ab', 'A', 'Bb', 'B']; const COLORS = ['#f59e0b', '#10b981', '#8b5cf6', '#6366f1', '#38bdf8', '#94a3b8'];
export default function ArrangerPanel() {
  const [key, setKey] = useState('F'); const [mode, setMode] = useState<'major' | 'minor'>('minor'); const [style, setStyle] = useState('ECM Ballad'); const [seed, setSeed] = useState(2026);
  const result = useMemo(() => arrange({ key, mode, style, seed }), [key, mode, style, seed]); const slug = `${key}-${mode}-${style}`.toLowerCase().replace(/[^a-z0-9]+/g, '-');
  return <div className="max-w-[1500px] mx-auto w-full space-y-5">
    <section className="rounded-2xl border border-slate-700/70 bg-slate-900/90 p-5 shadow-2xl"><div className="flex flex-col lg:flex-row gap-5 lg:items-end lg:justify-between"><div><div className="flex items-center gap-2 text-amber-400 text-sm font-semibold"><Sparkles className="w-4 h-4"/> AiXEL 32-Bar Arranger</div><h2 className="text-2xl md:text-3xl font-bold text-white mt-1">Modern chamber-string sextet</h2><p className="text-slate-400 mt-1 max-w-2xl">AABA form, lyrical voice leading, 3rds and 7ths at the centre, and 9 / #11 / 13 colours in the crown.</p></div><div className="grid grid-cols-2 md:grid-cols-4 gap-2 min-w-[min(100%,650px)]"><label className="control-label">Key<select value={key} onChange={event => setKey(event.target.value)}>{KEYS.map(value => <option key={value}>{value}</option>)}</select></label><label className="control-label">Mode<select value={mode} onChange={event => setMode(event.target.value as 'major' | 'minor')}><option value="minor">Minor</option><option value="major">Major</option></select></label><label className="control-label">Style<select value={style} onChange={event => setStyle(event.target.value)}>{STYLE_PRESETS.map(value => <option key={value.name}>{value.name}</option>)}</select></label><button onClick={() => setSeed(Math.floor(Math.random() * 999999))} className="export-button bg-amber-500 text-slate-950"><RefreshCw className="w-4 h-4"/> New take</button></div></div></section>
    <section className="rounded-2xl border border-slate-700/70 bg-slate-900 p-4 md:p-6"><div className="flex flex-wrap justify-between gap-3 mb-4"><div><h3 className="text-white text-lg font-bold">Score overview</h3><p className="text-slate-400 text-sm">{result.meter} · {result.tempo} BPM · seed {result.seed} · quality {result.quality}/100</p></div><div className="flex flex-wrap gap-2"><button className="export-button border-cyan-500 text-cyan-300" onClick={() => download(toMidi(result), `${slug}.mid`)}><Download className="w-4 h-4"/> MIDI</button><button className="export-button border-violet-500 text-violet-300" onClick={() => download(toMusicXml(result), `${slug}.musicxml`)}><Download className="w-4 h-4"/> MusicXML</button><button className="export-button border-amber-500 text-amber-300" onClick={() => download(toChart(result), `${slug}-chart.txt`)}><Download className="w-4 h-4"/> Chart</button></div></div><div className="overflow-x-auto pb-2"><div className="min-w-[1050px]"><div className="grid grid-cols-32 h-7 mb-2">{result.bars.map((bar, index) => <div key={bar.number} className={`text-center text-[10px] py-1 ${index < 8 ? 'bg-emerald-900' : index < 16 ? 'bg-cyan-900' : index < 24 ? 'bg-violet-900' : 'bg-amber-900'}`}>{index % 8 === 0 ? bar.section : ''}</div>)}</div><div className="relative h-[300px] rounded-xl bg-[#07111f] border border-slate-800 overflow-hidden">{Array.from({length: 33}, (_, index) => <div key={index} className="absolute top-0 bottom-0 border-l border-slate-800/70" style={{left: `${index / 32 * 100}%`}}/>)}{result.notes.map((note, index) => { const voiceIndex = VOICES.indexOf(note.voice); return <div key={index} title={`${note.voice} · MIDI ${note.midi} · bar ${note.bar}`} className="absolute rounded-sm opacity-90" style={{left: `${note.start / 32 * 100}%`, width: `${Math.max(note.duration / 32 * 100, .18)}%`, bottom: `${(note.midi - 27) / 68 * 100}%`, height: '5px', backgroundColor: COLORS[voiceIndex]}}/>; })}</div><div className="flex gap-4 mt-3">{VOICES.map((voice, index) => <span key={voice} className="text-xs text-slate-400 flex items-center gap-1"><i className="w-2 h-2 rounded-full" style={{background: COLORS[index]}}/>{voice}</span>)}</div></div></div></section>
    <section className="rounded-2xl border border-slate-700/70 bg-slate-900 p-4 md:p-6"><h3 className="text-white text-lg font-bold mb-3">32-bar harmonic map</h3><div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-8 gap-2">{result.bars.map(bar => <div key={bar.number} className="rounded-lg bg-slate-800 border border-slate-700 p-2 min-h-20"><div className="flex justify-between text-[10px] text-slate-500"><span>{bar.section}</span><span>{bar.number}</span></div><div className="text-white font-semibold mt-2 text-sm">{bar.chord}</div><div className="text-[10px] text-amber-400 mt-1">{bar.texture}</div></div>)}</div></section>
  </div>;
}
